<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class Admin2Controller extends AbstractController
{
    #[Route('/admin2', name: 'app_admin2')]
    public function index(): Response
    {
        return $this->render('admin2/index.html.twig', [
            'controller_name' => 'Admin2Controller',
        ]);
    }

    public function getAllUser(): ?UserInterface
    {
        return parent::getUser(); // TODO: Change the autogenerated stub
    }
}
